server:
  port: 8080
spring:
  config:
    activate:
      on-profile: localhost, default
  datasource:
    url: ${env.POSTGRES_URL}
    username: ${env.POSTGRES_USERNAME}
    password: ${env.POSTGRES_PASSWORD}
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
---
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: ${env.POSTGRES_URL}
    username: ${env.POSTGRES_USERNAME}
    password: ${env.POSTGRES_PASSWORD}
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
---
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: docker
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
---
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${env.POSTGRES_URL}
    username: ${env.POSTGRES_USERNAME}
    password: ${env.POSTGRES_PASSWORD}
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
